config/routes.rb
Rails.application.routes.draw do
  get 'expenses/new'
  get 'expenses/create'
  get 'expenses/edit'
  get 'expenses/update'
  get 'expenses/destroy'
  resources :businesspartners
  devise_for :users, :path => 'u'
  resources :users
  resources :expenses do
    collection do
      post ':type', action: :create, as: :create_type
      get 'new/:type', action: :new, as: :new_type
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root "users#home"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "SmartFlow", root_path, class: :"nav-link"%>
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Users", users_path, class: :"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "Business Partners", businesspartners_path, class: :"nav-link"%>
        </li>
        </li>
        <li class="nav-item">
        <%= link_to "Expenses", expenses_path, class: :"nav-link"%>
        </li>
    
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-xyz" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> 

<style>
  .user-info {
    background-color: #f8f8f8;
    border: 1px solid #ddd;
    padding: 15px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    margin: 20px;
    text-align: center;
  }

  .user-info a {
    text-decoration: none;
    color: #3498db;
    font-weight: bold;
  }

  .user-info a:hover {
    color: #2980b9;
  }
</style>

  <%= yield %> 
  </body>
</html>